### ISSUE TITLE
Black boxes border on Gtk2 (and some Gtk3 apps)

### ISSUE THREAD

**Issue by ghost** [godlyranchdressing/Adwaita-Slim#1]
The theme looks good overall but some borders seem off in apps like gdebi, menulibre, bleachbit, etc.
![pantallazo-2017-07-10 03-06-10](https://user-images.githubusercontent.com/24773698/28008586-bbe07866-651d-11e7-8ff3-f4dbadd70322.png)

**Comment by jcfeitosa** [comment]
Appearing on Fedora Gnome Shell too.
